import 'package:flutter/material.dart';

//class _Styles {
 // static Map<String, dynamic> content = {
    // @keyframes avatar_bounce{0%,100%{top:0}15%{top:6%}}
    // @keyframes avatar_clicked{0%,100%{transform:scale(1)}15%{transform:scale(1.2)}}.avatar{pointer-events:none;user-select:none;
    // position:relative;flex:0 0 auto;height:100%;width:100%;
    // image-rendering:-moz-crisp-edges;image-rendering:crisp-edges;
    // -ms-interpolation-mode:nearest-neighbor;
    // image-rendering:pixelated}.avatar.fit{width:100%;height:100%}
    // .avatar.clicked{animation:avatar_clicked 125ms ease-in-out 1}
    // .avatar .eyes.bounce,.avatar .mouth.bounce{animation:avatar_bounce 125ms ease-in-out 1}
    // .avatar .color{position:absolute;width:100%;height:100%;background-image:url(/img/avatar/color_atlas.gif);background-size:1000% 1000%}
    // .avatar .eyes{position:absolute;width:100%;height:100%;background-image:url(/img/avatar/eyes_atlas.gif);background-size:1000% 1000%}
    // .avatar .mouth{position:absolute;width:100%;height:100%;background-image:url(/img/avatar/mouth_atlas.gif);background-size:1000% 1000%}
    // .avatar .special{position:absolute;left:-33%;top:-33%;width:166%;height:166%;background-image:url(/img/avatar/special_atlas.gif);background-size:1000% 1000%}
    // .avatar .owner{position:absolute;width:50%;height:50%;left:-5%;top:-22%;z-index:2;background-image:url(/img/crown.gif);background-position:center;background-size:contain}

    // --vh:1vh;
    //   --BORDER_GAP:6px;
    //   --MOBILE_CHAT_MAXHEIGHT:200px;
    //   --PLAYERS_PER_PAGE:-1;
    //   --COLOR_TEXT_CANVAS_TRANSPARENT:#404040;
    //   --COLOR_PANEL_BG:rgba(12, 44, 150, 0.75);
    //   --COLOR_PANEL_LO:rgba(7, 36, 131, 0.75);
    //   --COLOR_PANEL_HI:#1640c9;
    //   --COLOR_PANEL_FOCUS:#ee9631;
    //   --COLOR_PANEL_BORDER:#040a33;
    //   --COLOR_PANEL_BORDER_FOCUS:#56b2fd;
    //   --COLOR_PANEL_TEXT:#f0f0f0;
    //   --COLOR_PANEL_TEXT_FOCUS:white;
    //   --COLOR_PANEL_TEXT_PLACEHOLDER:#9b9b9b;
    //   --COLOR_PANEL_BUTTON:#2a51d1;
    //   --COLOR_PANEL_BUTTON_HOVER:#1e44be;
    //   --COLOR_PANEL_BUTTON_ACTIVE:#1d40b4;
    //   --COLOR_TOOL_BASE:white;
    //   --COLOR_TOOL_HOVER:#c5c5c5;
    //   --COLOR_TOOL_ACTIVE:#ab66eb;
    //   --COLOR_TOOL_TEXT:#000;
    //   --COLOR_TOOL_SIZE_BASE:white;
    //   --COLOR_TOOL_SIZE_HOVER:#c5c5c5;
    //   --COLOR_TOOL_SIZE_ACTIVE:#ab66eb;
    //   --COLOR_INPUT_HOVER:white;
    //   --COLOR_INPUT_BORDER_FOCUS:#56b2fd;
    //   --COLOR_TOOL_TIP_BG:#4571ff;
    //   --COLOR_GAMEBAR_TEXT:#000;
    //   --COLOR_GAMEBAR_ROUND_TEXT:#000;
    //   --COLOR_GAMEBAR_WORD_DESCRIPTION:#363636;
    //   --COLOR_CHAT_TEXT_BASE:#000;
    //   --COLOR_CHAT_TEXT_GUESSED:#56CE27;
    //   --COLOR_CHAT_TEXT_CLOSE:#e2cb00;
    //   --COLOR_CHAT_TEXT_DRAWING:#3975CE;
    //   --COLOR_CHAT_TEXT_JOIN:#56CE27;
    //   --COLOR_CHAT_TEXT_LEAVE:#CE4F0A;
    //   --COLOR_CHAT_TEXT_OWNER:#ffa844;
    //   --COLOR_CHAT_TEXT_GUESSCHAT:#7dad3f;
    //   --COLOR_CHAT_BG_BASE:#fff;
    //   --COLOR_CHAT_BG_ALT:#ececec;
    //   --COLOR_CHAT_SCROLLBAR:#7e7e7e;
    //   --COLOR_CHAT_SCROLLBAR_THUMB:#c7c7c7;
    //   --COLOR_CHAT_BG_GUESSED_BASE:#e7ffdf;
    //   --COLOR_CHAT_BG_GUESSED_ALT:#cfffbd;
    //   --COLOR_CHAT_INPUT_COUNT:#000;
    //   --COLOR_PLAYER_TEXT_BASE:#000;
    //   --COLOR_PLAYER_ME:#4998ff;
    //   --COLOR_PLAYER_ME_GUESSED:#0048b5;
    //   --COLOR_PLAYER_BG_BASE:#fff;
    //   --COLOR_PLAYER_BG_ALT:#ececec;
    //   --COLOR_PLAYER_BG_GUESSED_BASE:#5bdd4a;
    //   --COLOR_PLAYER_BG_GUESSED_ALT:#48c737
    // }
    //html{box-sizing:border-box}*,:after,:before{box-sizing:inherit}
    //body{font-family:Nunito,sans-serif;padding:0;margin:0;background-color:#124da5;background-image:url(/img/background.png);
    //background-repeat:repeat;background-size:350px;height:100%;-ms-interpolation-mode:nearest-neighbor;image-rendering:-webkit-optimize-contrast;image-rendering:-moz-crisp-edges;
    //image-rendering:pixelated}a{color:#b4baff}
    //button{font:inherit;font-size:inherit;color:inherit;padding:0;margin:0;cursor:pointer;border:0;font-weight:800;color:var(--COLOR_PANEL_TEXT);
    //-webkit-appearance:none;-moz-appearance:none;appearance:none;text-decoration:none}button:disabled{cursor:not-allowed;opacity:.7}
    //input::placeholder{color:var(--COLOR_PANEL_TEXT_PLACEHOLDER)}input,select,textarea{font:inherit;flex:0 0 auto;height:32px;width:100%;color:var(--COLOR_INPUT_TEXT);
    //background-color:var(--COLOR_INPUT_BG);border:1px solid var(--COLOR_INPUT_BORDER);border-radius:var(--BORDER_RADIUS);transition:background-color .12s ease,border-color .12s ease}
    //input:focus,select:focus,textarea:focus{outline:0;background-color:var(--COLOR_INPUT_HOVER);border-color:var(--COLOR_INPUT_BORDER_FOCUS);box-shadow:0 0 10px -4px var(--COLOR_INPUT_BORDER_FOCUS)}
    //input:hover:not(:disabled),select:hover:not(:disabled),textarea:hover:not(:disabled){background-color:var(--COLOR_INPUT_HOVER)}input:disabled,select:disabled,textarea:disabled{cursor:not-allowed;opacity:.7}
    //input:invalid,select:invalid,textarea:invalid{border-color:red}input[type=range]:focus{box-shadow:none}input[type=checkbox]{appearance:none;-webkit-appearance:none;-moz-appearance:none;margin:0;padding:0;width:1.15em;height:1.15em;transition:none;display:grid;
    //place-content:center}input[type=checkbox]::before{content:"";width:0;height:0;border-radius:var(--BORDER_RADIUS);transition:width 50ms ease-in-out,height 50ms ease-in-out;box-shadow:inset 1em 1em var(--COLOR_INPUT_TEXT)}input[type=checkbox]:checked::before{width:1em;height:1em}
    //.crisp{-ms-interpolation-mode:nearest-neighbor;image-rendering:-webkit-optimize-contrast;image-rendering:-moz-crisp-edges;image-rendering:pixelated}.shadow{box-shadow:0 0 2px 2px rgba(0,0,0,.2)}.unselectable{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;
    //-ms-user-select:none;-o-user-select:none;user-select:none;pointer-events:none}.dots{width:100%;height:100%;display:flex;justify-content:center}.dots .dot{cursor:pointer;height:100%;width:auto;aspect-ratio:1;opacity:.3;transition:opacity .1s ease-in-out;display:flex;justify-content:center;align-items:center}.dots
    //.dot.active,.dots .dot:hover{opacity:1}.dots .dot .inner{width:44%;height:44%;background-color:#fff;border-radius:999px;box-shadow:0 0 3px rgba(0,0,0,.6)}.dots .dot.active .inner{width:57%;height:57%}@keyframes tooltip_introduce{0%{opacity:0;transform:scale(0)}100%{opacity:1;transform:scale(1)}}.tooltip{pointer-events:none;position:absolute;z-index:10000;filter:drop-shadow(2px 2px 2px rgba(0, 0, 0, .15));
    //animation:tooltip_introduce .2s ease-in-out}.tooltip.N .tooltip-content{transform:translate(-50%,calc(-100% - 10px - 4px))}.tooltip.N .tooltip-arrow{top:-14px;left:calc(50% - 10px);border-left:10px solid transparent;border-right:10px solid transparent;border-top:10px solid var(--COLOR_TOOL_TIP_BG)}.tooltip.S .tooltip-content{transform:translate(-50%,14px)}.tooltip.S .tooltip-arrow{left:calc(50% - 10px);
    //top:4px;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:10px solid var(--COLOR_TOOL_TIP_BG)}.tooltip.E .tooltip-content{transform:translate(14px,-50%)}.tooltip.E .tooltip-arrow{top:calc(50% - 10px);left:4px;border-top:10px solid transparent;border-bottom:10px solid transparent;border-right:10px solid var(--COLOR_TOOL_TIP_BG)}.tooltip.W .tooltip-content{transform:translate(calc(-100% - 10px - 4px),-50%)}.tooltip.W .tooltip-arrow{top:calc(50% - 10px);
    //left:-14px;border-top:10px solid transparent;border-bottom:10px solid transparent;border-left:10px solid var(--COLOR_TOOL_TIP_BG)}.tooltip .tooltip-arrow{position:absolute;width:0;height:0}.tooltip .tooltip-content{position:absolute;color:var(--COLOR_PANEL_TEXT);border-radius:var(--BORDER_RADIUS);padding:7px;background-color:var(--COLOR_TOOL_TIP_BG);text-shadow:1px 1px 0 #00000038;text-align:center;font-size:13px;font-weight:700;white-space:pre}@keyframes setting_icon_introduce{0%{opacity:0;transform:scale(0) translateY(-30px)}100%{opacity:1;transform:scale(1) translateY(0)}}
    //@keyframes setting_content{0%{opacity:0}100%{opacity:1}}#game-settings{z-index:20;position:absolute;width:48px;height:48px;right:0;top:0;display:flex;justify-content:center;align-items:center;overflow:hidden}#game-settings .icon{position:relative;cursor:pointer;width:42px;height:42px;background-image:url(/img/settings.gif);background-size:contain;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3));transition:transform .1s ease-in-out}#game-settings .icon:hover{transform:scale(1.1)}#game-settings.open .content{display:block}#game-settings .content{display:none;position:relative;border-radius:var(--BORDER_RADIUS);margin:-4px;margin-top:4px;padding:4px;animation:setting_content .15s ease-in-out 0s 1 normal both}#audio{cursor:pointer;width:48px;height:48px;animation:setting_icon_introduce .15s ease-in-out;animation-fill-mode:both;animation-delay:0s}#audio .icon{width:100%;height:100%;background-size:contain;background-image:url(/img/audio.gif);transition:transform 70ms ease;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}#audio.off .icon{background-image:url(/img/audio_off.gif)}#audio:hover .icon{transform:scale(1.2)}#lightbulb{cursor:pointer;width:48px;height:48px;animation:setting_icon_introduce .15s ease-in-out;animation-fill-mode:both;animation-delay:35ms}#lightbulb .icon{width:100%;height:100%;background-size:contain;background-image:url(/img/bulb.gif);transition:transform 70ms ease;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}#lightbulb.off .icon{background-image:url(/img/bulb_off.gif)}#lightbulb:hover .icon{transform:scale(1.2)}
    //#hotkeys{cursor:pointer;width:48px;height:48px;animation:setting_icon_introduce .15s ease-in-out;animation-fill-mode:both;animation-delay:70ms}#hotkeys .icon{width:100%;height:100%;background-size:contain;background-image:url(/img/key.gif);transition:transform 70ms ease;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}#hotkeys.off .icon{background-image:url(/img/key.gif)}#hotkeys:hover .icon{transform:scale(1.2)}#load{display:none;position:fixed;z-index:9998;left:0;top:0;right:0;bottom:0;animation:loadopacity .3s ease-in-out;background-color:rgba(0,0,0,.75);backdrop-filter:blur(6px)}@keyframes loadopacity{0%{opacity:0;backdrop-filter:blur(0)}100%{opacity:100%;backdrop-filter:blur(6px)}}@keyframes loadpos{0%{opacity:0;top:35%}100%{opacity:100%;top:50%}}#load .container{position:absolute;left:50%;top:50%;animation:loadpos .3s ease-in-out}@keyframes loadrot{0%{transform:rotate(0)}100%{transform:rotate(360deg)}}#load .container .icon{position:absolute;width:128px;height:128px}#load .container .icon .graphic{position:absolute;left:-50%;top:-50%;width:100%;height:100%;background-image:url(/img/load.gif);background-size:contain;filter:drop-shadow(0 0 5px rgba(0, 0, 0, .5));animation:loadrot .8s ease-in-out 0s infinite}@supports (backdrop-filter:blur()){#load{background-color:rgba(255,255,255,.2)}}
    //html[dat-theme=dark]{--COLOR_PANEL_BG:rgba(8, 36, 129, 0.75);--COLOR_PANEL_LO:rgba(7, 36, 131, 0.75);--COLOR_PANEL_HI:#1640c9;--COLOR_PANEL_FOCUS:#ee9631;--COLOR_PANEL_BORDER:#040a33;--COLOR_PANEL_BORDER_FOCUS:#56b2fd;--COLOR_PANEL_TEXT:#f0f0f0;--COLOR_PANEL_TEXT_FOCUS:white;--COLOR_PANEL_TEXT_PLACEHOLDER:#aaaaaa;--COLOR_INPUT_BG:#0b2a61;--COLOR_INPUT_HOVER:#0b2a61;--COLOR_INPUT_TEXT:white;--COLOR_INPUT_BORDER:#214688;--COLOR_INPUT_BORDER_FOCUS:#56b2fd;--COLOR_TOOL_BASE:#3e50b6;--COLOR_TOOL_HOVER:#2f3f9b;--COLOR_TOOL_TEXT:white;--COLOR_TOOL_SIZE_BASE:gray;--COLOR_TOOL_SIZE_HOVER:darkgray;--COLOR_TOOL_SIZE_ACTIVE:gray;--COLOR_GAMEBAR_TEXT:white;--COLOR_GAMEBAR_ROUND_TEXT:white;--COLOR_GAMEBAR_WORD_DESCRIPTION:#c2c2c2;--COLOR_CHAT_TEXT_BASE:#fff;--COLOR_CHAT_BG_BASE:rgba(7, 36, 131, 0.75);--COLOR_CHAT_BG_ALT:rgba(7, 36, 131, 0.75);--COLOR_CHAT_BG_GUESSED_BASE:#026130;--COLOR_CHAT_BG_GUESSED_ALT:#004622;--COLOR_CHAT_INPUT_COUNT:white;--COLOR_PLAYER_TEXT_BASE:#fff;--COLOR_PLAYER_BG_BASE:rgba(7, 36, 131, 0.75);--COLOR_PLAYER_BG_ALT:rgba(7, 36, 131, 0.75);--COLOR_PLAYER_BG_GUESSED_BASE:rgba(2, 97, 48, 0.75);--COLOR_PLAYER_BG_GUESSED_ALT:rgba(2, 97, 48, 0.75)}html[data-theme=dark] body{background-image:url(/img/background_dark.png)}html[data-theme=dark] #game-players .player .icons .icon{filter:invert(1)}html[data-theme=dark] #game-canvas,html[data-theme=dark] #game-toolbar .color-picker{filter:brightness(.75)}body.snow::before{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;pointer-events:none;content:'';position:fixed;top:0;left:0;width:100%;height:100%;background:radial-gradient(transparent 0,transparent 70%,rgba(89,194,255,.36) 100%)}canvas.snow{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;pointer-events:none;position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1000;opacity:.9;filter:drop-shadow(0 0 4px #000)}
    //body .snow{background-image:url(/img/snow.gif);position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1000;background-size:cover;mix-blend-mode:plus-lighter;opacity:.8;filter:drop-shadow(0 0 4px #000)}.ad-1{width:728px;height:90px}.ad-2{width:300px;height:250px}#game{display:none;flex-direction:column;align-items:center;margin-left:8px;margin-right:8px}#game-logo{grid-area:logo;display:flex;justify-content:space-between;align-items:flex-end;height:90px}#game-logo a img{width:320px;height:auto;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .25))}
    //#game-wrapper{height:100%;font-size:14px;display:grid;grid-gap:var(--BORDER_GAP);gap:var(--BORDER_GAP);grid-template-areas:"logo    logo   logo" "bar     bar    bar" "players canvas chat" ".       tools  .";grid-template-columns:min-content auto auto;grid-template-rows:min-content 48px min-content min-content}#game-wrapper.toolbar-hidden #game-toolbar{visibility:hidden}#game-wrapper.room #game-invite{display:unset}#game-container{display:flex;flex-direction:row;justify-content:center;position:relative}#game-info{cursor:pointer;position:absolute;display:flex;align-items:center;background-image:url(/img/info.gif);right:8px;top:8px;width:32px;height:32px;color:#b4b4b4;font-size:30px;opacity:.7}#game-info:hover{opacity:1}#game-players{grid-area:players;position:relative;flex:0 0 auto;width:200px;border-radius:var(--BORDER_RADIUS);display:flex;flex-direction:column}#game-players .player-amount{display:none;position:absolute;font-size:1rem;font-weight:700;bottom:100%;left:0;text-shadow:0 0 3px rgba(0,0,0,.6);color:#fff;width:100%;text-align:center}#game-players .player-amount p{font-size:.8rem;margin:0;margin-bottom:-6px}#game-players .player-amount b:nth-child(4),
    //
    //
    //#game-players .player-amount span{font-size:.8rem;color:#ddd}
    //#game-players .player-amount span{margin:0 2px 0 2px}

    //#game-players .players-footer{width:100%;height:32px;position:relative;flex:0 0 auto;display:flex}#game-players .players-list{flex:1 1 auto;display:flex;flex-direction:column;height:32px}#game-players .players-list .player{cursor:pointer;position:relative;width:100%;height:48px;color:var(--COLOR_PLAYER_TEXT_BASE)}#game-players .players-list .player.first{border-top-left-radius:var(--BORDER_RADIUS);border-top-right-radius:var(--BORDER_RADIUS)}#game-players .players-list .player.last{border-bottom-left-radius:var(--BORDER_RADIUS);border-bottom-right-radius:var(--BORDER_RADIUS)}#game-players .players-list .player:not(.odd){background-color:var(--COLOR_PLAYER_BG_BASE)}#game-players .players-list .player:not(.odd).guessed{background-color:var(--COLOR_PLAYER_BG_GUESSED_BASE)}
    //#game-players .players-list .player.odd{background-color:var(--COLOR_PLAYER_BG_ALT)}#game-players .players-list .player.odd.guessed{background-color:var(--COLOR_PLAYER_BG_GUESSED_ALT)}#game-players .players-list .player:hover .avatar{transform:scale(1.1)}#game-players .players-list .player.guessed .player-name.me{color:var(--COLOR_PLAYER_ME_GUESSED)}#game-players .players-list .player.admin{color:#d30707}#game-players .players-list .player .player-bubble{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;pointer-events:none;z-index:2;position:absolute;display:flex;align-items:center;left:100%;top:6%;bottom:6%;animation:bubble_fadeout 1.5s ease-out 0s 1;animation-fill-mode:forwards;filter:drop-shadow(1px 1px 1px rgba(0, 0, 0, .3))}@keyframes bubble_fadeout{0%,75%{opacity:1}100%{opacity:0}}#game-players .players-list .player .player-bubble .arrow{height:40%;width:auto;aspect-ratio:.5;background-color:#e4e4e4;clip-path:polygon(0 50%,100% 0,100% 100%)}#game-players .players-list .player .player-bubble .content{max-width:20ch;height:100%;padding-left:.8ch;padding-right:.8ch;border-radius:var(--BORDER_RADIUS);color:#000;
    //background-color:#e4e4e4;display:flex;flex-direction:column;justify-content:center}#game-players .players-list .player .player-bubble .content .text{flex:0 0 auto;font-size:1em;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#game-players .players-list .player .player-bubble .content .icon{width:auto;height:90%;aspect-ratio:1;background-size:cover}#game-players .players-list .player .player-icons{position:absolute;bottom:0;left:4px;display:flex}@keyframes icon_introduce{0%{transform:translateY(-8px);opacity:0}100%{transform:translateY(0);opacity:.7}}#game-players .players-list .player .player-icons .icon{display:none;flex:0 0 auto;opacity:.7;width:24px;height:24px;margin-right:4px;background-size:cover;animation:icon_introduce .21s ease-in-out}#game-players .players-list .player .player-icons .icon.owner{background-image:url(/img/owner.gif)}#game-players .players-list .player .player-icons .icon.muted{background-image:url(/img/mute.gif)}#game-players .players-list .player .player-icons .icon.visible{display:block}#game-players .players-list .player .player-avatar-container{position:absolute;right:0;top:-1px;width:48px;height:48px}#game-players .players-list .player .avatar{transition:transform .1s ease-in-out}#game-players .players-list .player .avatar .drawing{image-rendering:crisp-edges;display:none;position:absolute;width:42px;height:42px;right:30px;top:3px;z-index:2;background-image:url(/img/pen.gif);background-size:contain;animation:icon_drawing 1s ease infinite;-webkit-animation:icon_drawing 1s ease infinite}
    //@keyframes icon_drawing{0%,100%{transform:rotate(-5deg)}50%{transform:rotate(5deg)}}#game-players .players-list .player .player-info{width:100%;height:100%;position:relative;text-align:center;display:flex;flex-direction:column;justify-content:center}#game-players .players-list .player .player-name{width:100%;font-size:1em;line-height:1em;font-weight:700}#game-players .players-list .player .player-name.me{font-weight:bolder;color:var(--COLOR_PLAYER_ME)}#game-players .players-list .player .player-score{width:100%;font-size:.9em;line-height:1em}#game-players .players-list .player .player-tag{width:100%;font-size:.9em;line-height:1em;font-weight:700}#game-players .players-list .player .player-rank{position:absolute;font-weight:700;font-size:1.1em;top:5px;left:6px}#start-game{background-color:#53e237;text-shadow:2px 2px 0 #0000002b;transition:background-color 80ms;height:42px;border-radius:var(--BORDER_RADIUS);display:flex;justify-content:center;align-items:center;font-size:20px;width:100%}#start-game:hover:not(:disabled){background-color:#38c41c}#start-game:active:not(:disabled){background-color:#30aa19;padding-top:2px}#start-game img{width:30px;height:30px;margin-right:5px;vertical-align:middle;filter:drop-shadow(2px 2px 0 #0000005d)}#game-invite{grid-area:tools;display:none;width:100%;height:35px;order:1}#game-invite input{height:100%;border-radius:var(--BORDER_RADIUS) 0 0 var(--BORDER_RADIUS);text-align:center}#game-invite button{background-color:#2c8de7;text-shadow:2px 2px 0 #0000002b;transition:background-color 80ms;height:100%;border-radius:var(--BORDER_RADIUS);flex:0 0 15%;border-radius:0 var(--BORDER_RADIUS) var(--BORDER_RADIUS) 0}#game-invite button:hover:not(:disabled){background-color:#1671c5}#game-invite button:active:not(:disabled){background-color:#1361a9;padding-top:2px}#game-invite .title{width:100%;color:#fff;text-align:center;font-size:2em;font-weight:700}
    //#game-invite .link{flex:1 1 0;position:relative;height:100%;display:flex;flex-direction:row}#game-invite .link .input-container{flex:1 1 0;position:relative;height:100%;font-size:1.3em}
    //#game-invite .link .input-container .link-overlay{pointer-events:none;position:absolute;top:1px;left:1px;right:1px;bottom:1px;font-weight:700;border-radius:var(--BORDER_RADIUS) 0 0 var(--BORDER_RADIUS);opacity:1;background-color:#fff;display:flex;justify-content:center;align-items:center}
    //
    //#game-invite .link .input-container .link-overlay span{text-align:center;color:#2c8de7}

    //#game-invite .link .input-container:hover .link-overlay{opacity:0}#game-canvas .room{-webkit-user-select:text;-moz-user-select:text;-ms-user-select:text;user-select:text;display:none;color:var(--COLOR_PANEL_TEXT);position:relative;height:100%;width:100%;padding:var(--BORDER_GAP)}#game-canvas .room.show{display:unset}#game-canvas .room input,#game-canvas .room select{height:100%;font-size:1em}#game-canvas .room textarea{flex:1 1 auto;font-size:1.1em;width:100%;resize:none;border-radius:var(--BORDER_RADIUS);margin-top:calc(var(--BORDER_GAP)/ 2)}#game-canvas .room button{font-size:1.8em;height:10%}#game-canvas .room .game-room-name{flex:0 1 auto;position:relative;font-weight:bolder;font-size:1.2em}#game-canvas .room .game-room-description{flex:0 1 auto;font-size:.8em;font-style:italic;color:#d3d3d3}#game-canvas .room .game-room-checkbox{position:absolute;top:0;right:0;bottom:0;display:flex;justify-content:flex-end}#game-canvas .room .game-room-checkbox label{font-size:.8em;padding-right:var(--BORDER_GAP)}#game-canvas .room .game-room-checkbox input[type=checkbox]{aspect-ratio:1;width:auto;height:100%}#game-canvas .room .game-room-group.customwords{height:calc(38% - var(--BORDER_GAP) * 2);position:relative;display:flex;flex-direction:column;margin-top:var(--BORDER_GAP);margin-bottom:var(--BORDER_GAP)}#game-canvas .room .game-room-group{height:52%}
    //#game-canvas .room .game-room-group .items{height:100%;display:flex;flex-direction:column;justify-content:space-between}#game-canvas .room .game-room-group .items .item{height:calc(100% / 7 - var(--BORDER_GAP)/ 2);flex:0 0 auto;display:flex;flex-direction:row}#game-canvas .room .game-room-group .items .item .key{flex:1 1 0;display:flex;align-items:center}#game-canvas .room .game-room-group .items .item .key img{height:100%;width:auto;vertical-align:middle;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}
    
    //#game-canvas .room .game-room-group .items .item .key span{margin-left:.5em;flex:0 0 auto}
    //
    //#game-canvas .room .game-room-group .items .item .value{flex:0 0 45%}#game-chat{-webkit-user-select:text;-moz-user-select:text;-ms-user-select:text;user-select:text;grid-area:chat;display:flex;flex-direction:column;flex:1 0 auto;font-size:1em;width:300px}#game-chat .chat-container{display:flex;flex-direction:column;flex:1 1 auto;box-sizing:border-box;padding-bottom:.2em;background-color:var(--COLOR_CHAT_BG_BASE);border-radius:var(--BORDER_RADIUS)}#game-chat .chat-container .chat-content{flex:1 1 auto;height:32px;padding-top:.2em;word-wrap:break-word;overflow-y:auto;color:var(--COLOR_CHAT_TEXT_BASE)}@keyframes chat_msg{0%{opacity:0}100%{opacity:1}}#game-chat .chat-container .chat-content p{padding:.2em;margin:0;opacity:1;animation:chat_msg .1s ease-in-out 1}#game-chat .chat-container .chat-content p:nth-child(even){background-color:var(--COLOR_CHAT_BG_ALT)}#game-chat .chat-container .chat-content p.guessed{background-color:var(--COLOR_CHAT_BG_GUESSED_BASE)}#game-chat .chat-container .chat-content p.guessed:nth-child(even){background-color:var(--COLOR_CHAT_BG_GUESSED_ALT)}#game-chat .chat-container form{position:relative;font:inherit;margin:0;padding:0 .2em 0 .2em}#game-chat .chat-container form .characters{font-weight:700;position:absolute;right:1em;font-size:.9em;color:var(--COLOR_CHAT_INPUT_COUNT);top:1em;opacity:0;transition:top 70ms ease-in-out,opacity 70ms ease-in-out}#game-chat .chat-container form .characters.visible{top:.5em;opacity:1}#game-chat .chat-container form input{font:inherit;flex:0 0 auto;height:2.2em;width:100%;padding:.2em;padding-right:2em}#game-rate{position:absolute;top:4px;right:100px}@keyframes rate_introduce{0%,80%{opacity:0;top:-16px}100%{opacity:.6;top:0}}#game-rate .like{background-image:url(/img/thumbsup.gif)}#game-rate .dislike{background-image:url(/img/thumbsdown.gif);left:48px;animation-delay:.25s}
    //#game-rate .dislike,#game-rate .like{cursor:pointer;background-size:contain;z-index:999;position:absolute;width:48px;height:48px;opacity:.6;transition:transform 125ms ease,opacity 125ms ease;animation:rate_introduce 2s ease-in-out}
    //#game-rate .dislike:hover,#game-rate .like:hover{opacity:1;transform:scale(1.1)}#game-canvas{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;touch-action:none;flex:1 1 auto;background-color:#fff;border-radius:var(--BORDER_RADIUS);grid-area:canvas;overflow:hidden;position:relative}#game-canvas canvas{width:100%;height:auto;image-rendering:pixelated}#game-canvas .overlay{pointer-events:none;position:absolute;top:0;opacity:0;width:100%;height:100%;background-color:rgba(3,8,29,.8)}#game-canvas .overlay.show{opacity:1;pointer-events:all}#game-canvas .overlay-content{font-size:1em;position:absolute;width:100%;height:100%;top:-100%;text-shadow:0 0 3px rgba(0,0,0,.6);color:#fff;display:flex;flex-direction:column;justify-content:center;align-items:center}#game-canvas .overlay-content .result,#game-canvas .overlay-content .reveal,#game-canvas .overlay-content .text,#game-canvas .overlay-content .words{display:none}#game-canvas .overlay-content .result.show,#game-canvas .overlay-content .reveal.show,#game-canvas .overlay-content .text.show,#game-canvas .overlay-content .words.show{display:flex}#game-canvas .overlay-content .text{color:#fff;font-size:2.5em;flex-direction:column;align-items:center}#game-canvas .overlay-content .words{justify-content:center;flex-wrap:wrap;width:100%}@keyframes word_introduce{0%{opacity:0;transform:translate(0,-40%)}100%{opacity:1;transform:translate(0,0)}}#game-canvas .overlay-content .words .word{cursor:pointer;flex:0 0 auto;padding:0 .35em;margin:.35em;font-size:1.8em;font-weight:bolder;background-color:rgba(0,0,0,0);border:.15em solid #fff;border-radius:var(--BORDER_RADIUS);color:#fff;transition:background-color .1s,color .1s;animation:word_introduce .25s ease-in-out 0s 1 normal both}#game-canvas .overlay-content .words .word:hover{background-color:#fff;color:var(--COLOR_TEXT_CANVAS_TRANSPARENT);text-shadow:none}#game-canvas .overlay-content .reveal{flex-direction:column;align-items:center;width:100%;font-size:1.4em}#game-canvas .overlay-content .reveal p{font-weight:400;font-size:1.5em;margin:0}
    
    //#game-canvas .overlay-content .reveal p span.word{font-weight:700;color:#ffdfb4;margin-left:1ch}
    //
    //#game-canvas .overlay-content .reveal .reason{color:#d6d6d6;margin-bottom:1.5em;font-size:1em}
    //#game-canvas .overlay-content .reveal .player-container{display:flex;flex-direction:column;width:23ch}#game-canvas .overlay-content .reveal .player-container .player{font-size:1em;width:100%;display:flex;margin-bottom:-.3em}
    //#game-canvas .overlay-content .reveal .player-container .player .name{flex:1 1 80%}#game-canvas .overlay-content .reveal .player-container .player .score{text-align:end;flex:0 0 20%;font-weight:700;color:#17db17}#game-canvas .overlay-content .reveal .player-container .player .score.zero{color:#e01313}
    //#game-canvas .overlay-content .result{flex-direction:column;justify-content:center;align-items:center;width:100%;height:100%;position:relative}#game-canvas .overlay-content .result .message{display:flex;align-items:center;height:25%;font-size:2em}#game-canvas .overlay-content .result .message .winner-name{color:#ffdfb4}#game-canvas .overlay-content .result .avatar-container{position:relative}#game-canvas .overlay-content .result .avatar-container .avatar{position:absolute}#game-canvas .overlay-content .result .avatar-container .avatar.winner{transform-origin:50% 100%;animation:player_winner 3.8s ease 0s infinite}@keyframes player_winner{0%{transform:rotate(0) scale(1,1) translate(0,0)}5%,8%{transform:rotate(0) scale(1.2,.8) translate(0,0)}14%,16%{transform:rotate(20deg) scale(.8,1.2) translate(10%,-50%)}24%,26%{transform:rotate(0) scale(1.4,.7) translate(0,0)}28%,38%{transform:rotate(0) scale(1,1) translate(0,0)}42%{transform:rotate(0) scale(1.2,.8) translate(0,0)}48%,50%{transform:rotate(-20deg) scale(.8,1.2) translate(-10%,-50%)}58%,60%{transform:rotate(0) scale(1.4,.7) translate(0,0)}100%,62%{transform:rotate(0) scale(1,1) translate(0,0)}}#game-canvas .overlay-content .result .trophy{z-index:-1;position:absolute;width:100%;height:100%;left:50%;background-image:url(/img/trophy.gif);background-size:cover;filter:drop-shadow(0 0 8px rgba(0, 0, 0, .25))}#game-canvas .overlay-content .result .ranks{width:100%;height:35%;display:flex;flex-wrap:wrap;justify-content:center;align-content:center;font-size:.9em}#game-canvas .overlay-content .result .rank{display:flex;flex-direction:column;align-items:center;position:relative;width:15%}#game-canvas .overlay-content .result .rank .avatar{width:65%;height:auto;aspect-ratio:1}#game-canvas .overlay-content .result .rank-place{color:#b4b4b4;font-weight:700;position:absolute;top:0;left:10%}#game-canvas .overlay-content .result .rank-name{flex:0 0 auto;width:100%;text-align:center;font-size:.9em}#game-canvas .overlay-content .result .rank-score{flex:0 0 auto;width:100%;text-align:center;font-size:.7em}
    //#game-canvas .overlay-content .result .podests{flex:0 0 auto;font-size:1em;display:flex;align-items:flex-end;justify-content:center;width:100%;height:40%;filter:drop-shadow(0 0 20px rgba(0, 0, 0, .3))}#game-canvas .overlay-content .result .podests .podest-1{display:flex;flex-direction:column;justify-content:flex-end;align-items:center;width:27.5%;height:100%;font-size:1em;text-align:center;font-weight:700;color:#ffc532;order:1;margin-left:var(--BORDER_GAP);margin-right:var(--BORDER_GAP)}#game-canvas .overlay-content .result .podests .podest-1 .avatar-container{height:60%;width:auto;aspect-ratio:1}#game-canvas .overlay-content .result .podests .podest-1 .avatar-container .avatar{height:100%;width:auto;aspect-ratio:1;top:0}
    //#game-canvas .overlay-content .result .podests .podest-1 .border{display:flex;flex-direction:column;justify-content:center;position:relative;border:.5vh solid #ffc532;border-bottom:0;width:100%;height:40%}#game-canvas .overlay-content .result .podests .podest-1 .rank-place{position:absolute;font-size:1.3em;top:0;left:.3em;color:#ffc532}#game-canvas .overlay-content .result .podests .podest-1 .border{border-radius:1vh 1vh 0 0}#game-canvas .overlay-content .result .podests .podest-2{display:flex;flex-direction:column;justify-content:flex-end;align-items:center;width:23.75%;height:100%;font-size:1em;text-align:center;font-weight:700;color:silver;order:0}#game-canvas .overlay-content .result .podests .podest-2 .avatar-container{height:60%;width:auto;aspect-ratio:1}
    //#game-canvas .overlay-content .result .podests .podest-2 .avatar-container .avatar{height:100%;width:auto;aspect-ratio:1;top:0}
    //#game-canvas .overlay-content .result .podests .podest-2 .border{display:flex;flex-direction:column;justify-content:center;position:relative;border:.5vh solid silver;border-bottom:0;width:100%;height:30%}#game-canvas .overlay-content .result .podests .podest-2 .rank-place{position:absolute;font-size:1.3em;top:0;left:.3em;color:silver}#game-canvas .overlay-content .result .podests .podest-2 .border{border-radius:1vh 0 0 0;border-right:0}#game-canvas .overlay-content .result .podests .podest-3{display:flex;flex-direction:column;justify-content:flex-end;align-items:center;width:23.75%;height:100%;font-size:1em;text-align:center;font-weight:700;color:#be6029;order:2}#game-canvas .overlay-content .result .podests .podest-3 .avatar-container{height:60%;width:auto;aspect-ratio:1}#game-canvas .overlay-content .result .podests .podest-3 .avatar-container .avatar{height:100%;width:auto;aspect-ratio:1;top:0}#game-canvas .overlay-content .result .podests .podest-3 .border{display:flex;flex-direction:column;justify-content:center;position:relative;border:.5vh solid #be6029;border-bottom:0;width:100%;height:30%}#game-canvas .overlay-content .result .podests .podest-3 .rank-place{position:absolute;font-size:1.3em;top:0;left:.3em;color:#be6029}
    //#game-canvas .overlay-content .result .podests .podest-3 .border{border-radius:0 1vh 0 0;border-left:0}#game-bar{grid-area:bar;height:100%;font-size:1em;font-weight:700;color:#fff;text-align:center;position:relative;background-color:var(--COLOR_CHAT_BG_BASE);border-radius:var(--BORDER_RADIUS)}#game-bar .mobile{height:100%;font-size:var(--vh);font-weight:700;color:var(--COLOR_GAMEBAR_TEXT);pointer-events:none;display:none;position:absolute;top:0;left:0}#game-bar .mobile:hover{opacity:.3}#game-bar .mobile .drawtime{position:absolute}#game-bar .mobile .round{position:absolute;left:3em}#game-bar .mobile img{filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3));width:3em;height:3em}
    //
    //#game-bar .mobile span{font-size:1.5em;line-height:1.5em}
    //
    //#game-clock{pointer-events:none;position:absolute;width:64px;height:64px;background-image:url(/img/clock.gif);filter:drop-shadow(0 0 2px rgba(0, 0, 0, .15));color:#000;font-size:20px;line-height:3.6;font-weight:bolder;z-index:10;top:-10px;left:-8px;display:flex;justify-content:center;animation-name:none;animation-duration:.3s;animation-timing-function:ease-in-out;animation-iteration-count:1}#game-round{position:absolute;left:60px;top:14px;font-size:1.4em;color:var(--COLOR_GAMEBAR_ROUND_TEXT)}#game-word{height:100%;font-family:Inconsolata,monospace;font-weight:bolder;color:var(--COLOR_GAMEBAR_TEXT);text-align:center;position:relative;font-size:1em;margin-left:200px;margin-right:300px;display:flex;flex-direction:column;justify-content:center;align-items:center}#game-word .description{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;pointer-events:none;width:100%;font-size:1.1em;color:var(--COLOR_GAMEBAR_WORD_DESCRIPTION)}#game-word .description.waiting{top:16px}#game-word .word{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;pointer-events:none;width:100%;font-size:1.8em}
    //#game-word .hints{width:100%;font-size:1.8em;display:flex;justify-content:center;user-select:none}#game-word .hints .container{position:relative;display:flex;justify-content:center;gap:.08em}
    //#game-word .hints .container .hint{width:1ch;flex:0 0 auto;animation:0}@keyframes hint_uncover{0%,100%{color:#000;transform:translateY(0)}10%{color:#ffa844;transform:scale(1.35) translateY(-8px)}25%{transform:translateY(3px)}37%{transform:translateY(0)}}#game-word .hints .container .hint.uncover{animation:hint_uncover .8s ease-in-out 1}#game-word .hints .container .word-length{position:absolute;left:102%;top:-.2em;font-size:.55em;font-weight:700;white-space:nowrap}@keyframes rot_right{0%,100%{transform:rotate(0)}5%{transform:scale(1.15) rotate(25deg)}}@keyframes rot_left{0%,100%{transform:rotate(0)}5%{transform:scale(1.15) rotate(-25deg)}}.clickable{cursor:pointer;position:relative;color:var(--COLOR_TOOL_TEXT);background:var(--COLOR_TOOL_BASE);border-radius:var(--BORDER_RADIUS);margin-right:var(--BORDER_GAP)}@keyframes clickable_icon_clicked{0%{transform:scale(1.15);opacity:1}99%{opacity:1}100%{transform:scale(1)}}.clickable:last-child{margin-right:0}.clickable .icon{position:absolute;width:100%;height:100%;opacity:1;top:0;transition:top 65ms ease-in-out;animation:none}.clickable .key{cursor:pointer;opacity:.8;font-size:12px;font-weight:bolder;text-transform:uppercase;position:absolute;left:3px;top:-1px;-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;pointer-events:none}.clickable.selected .key,.clickable:hover .key{opacity:1}.clickable:hover{background:var(--COLOR_TOOL_HOVER)}.clickable.selected{background-color:var(--COLOR_TOOL_ACTIVE)}.clickable:hover .icon{top:-4px}.clickable.clicked .icon{animation:clickable_icon_clicked .1s ease-in-out 1}.clickable.selected .icon,.clickable:hover .icon{opacity:1}#game-toolbar{display:flex;justify-content:space-between;width:100%;height:48px;grid-area:tools;position:relative}#game-toolbar .tool{position:relative;width:48px;height:48px;overflow:hidden}#game-toolbar .tool .icon{opacity:.7;background-position:center;background-size:contain;background-repeat:no-repeat;filter:grayscale(70%) drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}
    //#game-toolbar .tool.selected .icon,#game-toolbar .tool:hover .icon{opacity:1;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}#game-toolbar .toolbar-group-actions,#game-toolbar .toolbar-group-colors,#game-toolbar .toolbar-group-tools{height:100%;display:flex;flex:1 1 auto}#game-toolbar .toolbar-group-tools{justify-content:center}#game-toolbar .toolbar-group-actions{justify-content:flex-end}
    //#game-toolbar .sizes{position:relative;width:48px;height:48px;display:flex;flex:0 1 auto;justify-content:space-between;margin-left:var(--BORDER_GAP)}#game-toolbar .sizes .container{display:none;position:absolute;overflow:hidden;border-radius:var(--BORDER_RADIUS) var(--BORDER_RADIUS) 0 0;filter:drop-shadow(0 0 5px rgba(0, 0, 0, .3));bottom:100%;left:0;right:0;flex-direction:column}#game-toolbar .sizes .container.open{display:flex}#game-toolbar .sizes .container .arrow{position:relative;order:1;width:48px;height:12px;background-color:var(--COLOR_TOOL_SIZE_BASE);clip-path:polygon(50% 100%,25% 0,75% 0)}#game-toolbar .sizes .size-preview{cursor:pointer;position:relative;width:100%;height:100%;border-radius:var(--BORDER_RADIUS);margin:0}#game-toolbar .sizes .size-preview .icon{background-position:center;background-repeat:no-repeat;background-image:url(/img/size.gif);filter:brightness(0) drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}#game-toolbar .sizes .size-preview.selected .icon,#game-toolbar .sizes .size-preview:hover .icon{filter:brightness(0) drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}#game-toolbar .sizes .current-size{position:absolute;top:0;width:100%;text-align:center;font-size:12px;font-weight:700;color:#000;z-index:5}#game-toolbar .sizes .size{cursor:pointer;position:relative;width:48px;height:48px;margin-right:0;border-radius:0;background-color:var(--COLOR_TOOL_SIZE_BASE)}#game-toolbar .sizes .size:first-of-type{border-radius:var(--BORDER_RADIUS) 0 0 var(--BORDER_RADIUS)}#game-toolbar .sizes .size:last-of-type{border-radius:0 0 var(--BORDER_RADIUS) var(--BORDER_RADIUS)}#game-toolbar .sizes .size .icon{background-position:center;background-repeat:no-repeat;background-image:url(/img/size.gif);filter:brightness(0) drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}#game-toolbar .sizes .size:hover{background-color:var(--COLOR_TOOL_SIZE_HOVER)}
    //#game-toolbar .sizes .size.selected{background-color:var(--COLOR_TOOL_SIZE_ACTIVE)}#game-toolbar .preview{cursor:pointer;position:relative;flex:0 0 auto;width:48px;height:48px;margin-right:var(--BORDER_GAP);overflow:hidden;border-radius:var(--BORDER_RADIUS)}#game-toolbar .preview.open .graphic-container,#game-toolbar .preview:hover .graphic-container{border-color:var(--COLOR_INPUT_BORDER_FOCUS)}#game-toolbar .preview.open .size,#game-toolbar .preview:hover .size{display:block}#game-toolbar .preview .size{display:none;position:absolute;top:100%;width:100%;height:24px;padding-top:4px;text-align:center;font-size:12px;font-weight:700;color:#fff;text-shadow:0 0 3px rgba(0,0,0,.6);z-index:5}#game-toolbar .preview .graphic-container{box-shadow:0 0 2px 2px rgba(0,0,0,.2);-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;pointer-events:none;position:absolute;width:48px;height:48px;border-radius:24px;border:4px dashed #d1d1d1af;background-color:#d1d1d13d}#game-toolbar .preview .graphic{position:absolute;top:50%;left:50%}#game-toolbar .preview .graphic .brush{position:relative;transform:translate(-50%,-50%);width:14px;height:14px;border-radius:32px;overflow:hidden}#game-toolbar .color-picker{display:flex;position:relative;height:100%}#game-toolbar .colors,#game-toolbar .colors-mobile{height:48px;overflow:hidden;border-radius:var(--BORDER_RADIUS)}#game-toolbar .colors .top .color::after,#game-toolbar .colors-mobile .top .color::after{border:3px solid rgba(0,0,0,.6)}#game-toolbar .colors .bottom .color::after,#game-toolbar .colors-mobile .bottom .color::after{border:3px solid rgba(255,255,255,.6)}#game-toolbar .colors .bottom,#game-toolbar .colors .top,#game-toolbar .colors-mobile .bottom,#game-toolbar .colors-mobile .top{display:flex;height:50%}#game-toolbar .colors .color,#game-toolbar .colors-mobile .color{position:relative;box-sizing:border-box;cursor:pointer;flex:1 1 auto;height:100%;width:24px}
    //#game-toolbar .colors .color::after,#game-toolbar .colors-mobile .color::after{display:none;content:'';position:absolute;left:2px;top:2px;right:2px;bottom:2px;border-radius:3px}#game-toolbar .colors .color:hover::after,#game-toolbar .colors-mobile .color:hover::after{display:inline}#game-toolbar .color-picker-mobile{width:48px;height:48px;display:none;flex:0 0 auto}#game-toolbar .color-picker-mobile .preview{margin:0}
    //#game-toolbar .colors-mobile{display:none;position:absolute;bottom:calc(100% + 3px + var(--BORDER_GAP));left:3px;right:3px;flex:1 1 auto;box-shadow:0 0 7px rgba(0,0,0,.5)}#game-toolbar .colors-mobile.open{display:none}#color-preview-primary,#color-preview-secondary{position:absolute;top:0;left:0;width:100%;height:100%}#game-keyboard{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;touch-action:none;pointer-events:none;display:none;position:fixed;flex:1 1 auto;bottom:0;height:30%;width:100%;max-width:70vh;font-size:2vh}#game-keyboard .material-icons{font-size:1em}#game-keyboard .keyboard-wrapper{pointer-events:all;position:absolute;top:calc(100% - 5vh);left:0;width:100%;height:100%;background-color:rgba(6,33,122,.9);backdrop-filter:blur(4px);transition:top .1s ease-in-out}#game-keyboard .settings{position:absolute;top:2px;right:2px;height:calc(5vh - 4px);width:auto;aspect-ratio:1;background-color:transparent}#game-keyboard .input{display:flex;width:100%;height:5vh;text-align:center;color:#fff;white-space:pre;justify-content:center;align-items:center}
    //
    //#game-keyboard .input span{display:none;font-size:1.5em}
    //
    //#game-keyboard .input .hidden{font-size:.75em}#game-keyboard .input .cursor{display:none;width:.2ch;margin-left:.25ch;height:80%;background-color:#fff;animation:keyboard_input_cursor 1s steps(2,start) 0s infinite}@keyframes keyboard_input_cursor{0%{opacity:1}100%{opacity:0}}#game-keyboard .keys{display:flex;flex-direction:column;width:100%;height:calc(100% - 5vh)}#game-keyboard .keys .row{display:flex;flex:1 1 auto;justify-content:center}#game-keyboard .keys .key{flex:1 1 1px;margin:.5vw;border-radius:.5vh;border:none;background-color:rgba(37,185,255,.26);color:#fff;outline:0;display:inline-flex;align-items:center;justify-content:center;-webkit-tap-highlight-color:none;text-shadow:.08em .08em #00000070;box-shadow:0 0 .5vh 0 #00000059}#game-keyboard .keys .key.enabled{color:var(--COLOR_INPUT_BORDER_FOCUS)}
    //#game-keyboard .keys .key:active{background-color:rgba(37,185,255,.12)}#game-keyboard .keys .key.wide{flex:1.35 1 auto}#game-keyboard .keys .key.extra-wide{flex:3.5 1 auto}#home{width:100%;min-height:100vh;display:flex;flex-direction:column;align-items:center}#home .ad-top{width:100%;height:100px;padding-left:64px;padding-right:64px;display:flex;justify-content:center}#home .ad-top .ad{flex:1 1 auto;max-width:970px;background-color:rgba(0,0,0,.5)}
    //#home .logo-big img{filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .25))}#home .logo-big .avatar-container{margin-top:10px;height:48px;display:flex;justify-content:center;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .25))}#home .logo-big .avatar-container .avatar{cursor:pointer;pointer-events:all;width:48px;height:48px}#home .news ::-webkit-scrollbar{width:14px;border-radius:7px;background-color:var(--COLOR_PANEL_LO)}#home .news ::-webkit-scrollbar-thumb{border-radius:7px;background-color:var(--COLOR_PANEL_HI)}#home .news .head{font-size:1.1em;font-weight:700;display:flex;align-items:baseline;border-bottom:1px solid var(--COLOR_PANEL_BORDER_FOCUS);margin-bottom:8px}#home .news .head .title{flex:1 1 auto}#home .news .head .date{flex:0 0 auto;font-size:.75em}#home .news .content{max-height:400px;overflow-y:auto}#home .news .content ul{font-size:.9em;margin:0;padding-left:24px}#home .panels{display:flex;width:100%}#home .panel{flex:0 0 auto;width:400px;background-color:var(--COLOR_PANEL_BG);border-radius:var(--BORDER_RADIUS);padding:15px}#home .panel-left{margin-right:8px;flex:1 1 50%;display:flex;align-items:flex-end;justify-content:flex-end}#home .panel-right{margin-left:8px;flex:1 1 50%;display:flex;flex-direction:column;justify-content:space-between}#home .socials{display:flex;flex-direction:column;align-items:center;color:#bebebe;font-size:.85em;margin-bottom:1em}#home .socials p{margin-top:0;margin-bottom:.25em}#home .socials .icons{display:flex}#home .socials .icons a{margin-left:.3em;margin-right:.3em}#home .socials .icons a img{opacity:.7;image-rendering:auto;height:1.8em;transition:transform 50ms ease-in-out}#home .socials .icons a img:hover{transform:scale(1.1);opacity:1}#home .container-name-lang{display:flex;flex-direction:row}#home input{height:34px;flex:1 1 auto;padding:2px 10px;font-weight:700}#home select{height:34px;flex:0 0 auto;width:120px;margin-left:4px;padding-left:2px}
    //#home .button-play{background-color:#53e237;text-shadow:2px 2px 0 #0000002b;transition:background-color 80ms;border-radius:var(--BORDER_RADIUS);font-size:2em;height:54px;width:100%}#home .button-play:hover:not(:disabled){background-color:#38c41c}#home .button-play:active:not(:disabled){background-color:#30aa19;padding-top:2px}#home .button-play img{width:45px;height:45px;margin-right:0;margin-bottom:6px;vertical-align:middle;filter:drop-shadow(2px 2px 0 #0000002b)}#home .button-create{background-color:#2c8de7;text-shadow:2px 2px 0 #0000002b;transition:background-color 80ms;height:40px;border-radius:var(--BORDER_RADIUS);width:100%;font-size:1.2em;font-weight:700;margin-top:10px}#home .button-create:hover:not(:disabled){background-color:#1671c5}#home .button-create:active:not(:disabled){background-color:#1361a9;padding-top:2px}#home .button-create img{width:30px;height:30px;margin-right:6px;margin-bottom:4px;vertical-align:middle;filter:drop-shadow(2px 2px 0 #0000002b)}#home .avatar-customizer{margin-top:10px;margin-bottom:10px;display:flex;justify-content:center;position:relative;background:rgba(0,0,0,.1);padding:8px;border-radius:var(--BORDER_RADIUS)}#home .avatar-customizer .randomize{cursor:pointer;position:absolute;width:32px;height:32px;right:4px;top:4px;opacity:.6;background-image:url(/img/randomize.gif);transition:opacity .15s ease,transform .15s ease}#home .avatar-customizer .randomize:hover{opacity:1;transform:scale(1.2)}#home .avatar-customizer .container{width:96px;height:96px}#home .avatar-customizer .arrows{display:flex;flex-direction:column;justify-content:space-around}#home .avatar-customizer .arrows .arrow{filter:drop-shadow(0 0 3px rgba(0, 0, 0, .15));flex:0 0 auto;cursor:pointer;width:34px;height:34px;background-image:url(/img/arrow.gif);background-size:200%;background-repeat:no-repeat}#home .avatar-customizer .arrows.left .arrow{background-position:0 0}#home .avatar-customizer .arrows.left .arrow:hover{background-position:100% 0}#home .avatar-customizer .arrows.right .arrow{background-position:0 100%}#home .avatar-customizer .arrows.right .arrow:hover{background-position:100% 100%}
    //#home #tutorial{position:relative;width:100%}#home #tutorial .pages{width:100%}#home #tutorial .pages .page{display:none;width:100%;flex-direction:column;align-items:center}#home #tutorial .pages .page.active{display:flex}#home #tutorial .pages .page img{width:100%;height:auto;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .25));animation:img_introduce .3s ease-in-out 1}@keyframes img_introduce{0%{top:-40px;opacity:0}100%{top:0;opacity:1}}#home #tutorial .pages .page .description{text-align:center;width:100%;height:3em}#home #tutorial .navigation{width:100%;height:25px}#home .bottom{width:100%;flex:1 0 auto;display:flex;flex-direction:column;justify-content:flex-end}
    //#home .bottom svg{width:100%;height:40px;fill:var(--COLOR_PANEL_BG)}#home .bottom .footer{padding-top:10px;padding-bottom:10px;width:100%;background-color:var(--COLOR_PANEL_BG)}#home .bottom .footer .notice{width:100%;text-align:center;font-size:.8em;color:#677af9}#home .bottom .footer .tos{width:100%;text-align:center}#home .bottom .footer .tos a{margin-left:4px;margin-right:4px}#home .bottom .footer .section-container{display:flex;justify-content:center;align-items:flex-start;width:100%}#home .bottom .footer .section-container .section{position:relative;font:inherit;color:var(--COLOR_PANEL_TEXT);width:320px;margin:10px}#home .bottom .footer .section-container .section .icon{position:absolute;top:18px;left:18px;width:32px;height:32px;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .25))}#home .bottom .footer .section-container .section h2{margin:0;margin-bottom:20px;width:100%;text-align:center}@keyframes frames_modal_opacity{0%{opacity:0}100%{opacity:1}}@keyframes frames_modal_position{0%{top:-21%}100%{top:0}}#modal{font-size:15px;display:none;overscroll-behavior:none;position:fixed;top:0;left:0;right:0;bottom:0;z-index:9999;background-color:rgba(0,0,0,.55);animation:frames_modal_opacity .21s ease-in-out}#modal input,#modal select{font-size:1em;height:2em}#modal button{font-size:1em;padding:0 .3em 0 .3em;width:100%;background-color:var(--COLOR_PANEL_BUTTON);text-shadow:2px 2px 0 #0000007a;transition:background-color .1s;height:2.5em;border-radius:var(--BORDER_RADIUS)}#modal button:hover:not(:disabled){background-color:var(--COLOR_PANEL_BUTTON_HOVER)}#modal button:active:not(:disabled){background-color:var(--COLOR_PANEL_BUTTON_ACTIVE)}#modal .modal-container-settings{width:500px;flex-direction:column}#modal .modal-container-settings button.reset{position:absolute;right:0;width:auto;height:100%}#modal .modal-container-settings .volume-value{margin-left:.5ch}#modal .modal-container-settings .group{margin-bottom:1em}#modal .modal-container-settings .group:last-child{margin-bottom:0}#modal .modal-container-settings .group .title{position:relative;display:flex;font-size:1.3em;font-weight:700;margin-bottom:.1em}
    //#modal .modal-container-settings .group .title .icon{display:inline;width:1.4em;height:1.4em;margin-right:.5ch;background-size:contain;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}#modal .modal-container-settings .group .title .icon.hotkeys{background-image:url(/img/key.gif)}#modal .modal-container-settings .group .title .icon.misc{background-image:url(/img/questionmark.gif)}#modal .modal-container-settings .group .title .icon.volume{background-image:url(/img/audio.gif)}#modal .modal-container-settings .group .title .icon.volume.muted{background-image:url(/img/audio_off.gif)}#modal .modal-container-settings .group .item{margin-bottom:.5em}#modal .modal-container-settings .group .item:last-child{margin-bottom:0}#modal .modal-container-settings .group #hotkey-list{display:flex}#modal .modal-container-settings .group #hotkey-list input{text-transform:uppercase}#modal .modal-container-settings .group #hotkey-list .item{margin-right:.5em}#modal .modal-container-settings .group #hotkey-list .item:last-child{margin-right:0}#modal .modal-container-info{width:410px;flex-direction:column;align-items:center;text-align:center}#modal .modal-container-info .message{display:flex;align-items:center;justify-content:center;height:8em}#modal .modal-container-player{width:350px;display:flex;justify-content:space-between}#modal .modal-container-player button{flex:1 1 auto;height:auto;margin-top:.5em}#modal .modal-container-player button.ban,#modal .modal-container-player button.kick{flex:1 1 auto}#modal .modal-container-player button.kick{margin-right:.5em}#modal .modal-container-player button#report-send{height:2.3em;margin-top:0}#modal .modal-container-player button#modal-player-button-invite{flex:0 0 auto;height:2.3em}#modal .modal-container-player .invite{flex-direction:column;justify-content:center;flex:1 1 auto}#modal .modal-container-player .invite .text{font-size:1.3em;text-align:center;flex:0 0 auto}#modal .modal-container-player .buttons{display:flex;flex-direction:column;flex:1 1 auto}#modal .modal-container-player .buttons .button-pair{flex:1 1 auto;height:auto}#modal .modal-container-player .buttons .button-pair button{margin-top:0}
    //#modal .modal-container-player .player{width:10em;height:10em;flex:0 0 auto;display:flex;flex-direction:column;align-items:center;justify-content:center}#modal .modal-container-player .player .name{width:100%;font:inherit;font-size:1em;font-weight:700;text-align:center}#modal .modal-container-player .report-menu{width:100%;display:flex;flex-direction:column}#modal .modal-container-player .report-menu .description{font-weight:700;font-size:1.2em;margin-bottom:1em}#modal .modal-container-player .report-menu .row{display:flex;margin-bottom:.35em}#modal .modal-container-player .report-menu .row label{flex:1 1 auto}#modal .modal-container-player .report-menu .row input{height:100%;width:auto;aspect-ratio:1}#modal .modal-container-room{flex-direction:column}#modal .modal-container-room .settings{display:flex;flex-direction:row;flex-wrap:wrap;width:600px;padding-bottom:4px;border-bottom:1px solid #ffffff61;margin-bottom:4px}#modal .modal-container-room .settings .setting{flex:0 0 50%;margin-bottom:7px}#modal .modal-container-room .settings .setting img{vertical-align:middle;filter:drop-shadow(3px 3px 0 rgba(0, 0, 0, .3))}
    //
    //#modal .modal-container-room .settings .setting span{line-height:0;margin-left:7px}
    //
    //#modal .modal-container-room .settings .setting .value{font-weight:700}#modal .modal-wrapper{position:relative;pointer-events:none;animation:frames_modal_position .21s ease-in-out;display:flex;justify-content:center;align-items:center;width:100%;height:100%}#modal .modal-container{pointer-events:all;position:relative;background-color:var(--COLOR_PANEL_BG);backdrop-filter:blur(4px);border-radius:10px;box-shadow:0 0 50px 0 rgba(0,0,0,.15);display:flex;flex-direction:column}#modal .modal-container .modal-title{flex:0 0 auto;position:relative;padding:.5em .5em 0 .5em;font-size:1.8em;font-weight:700;color:#fff}
    //#modal .modal-container .modal-title .close{position:absolute;top:0;right:.3ch;line-height:1;color:#aaa;font-size:1.5em}#modal .modal-container .modal-title .close:focus,#modal .modal-container .modal-title .close:hover{color:#fff;text-decoration:none;cursor:pointer}#modal .modal-container .modal-content{flex:1 1 auto;padding:1em;padding-top:.5em;white-space:pre-line;color:#fff}@media (max-width:1166px){#game-toolbar{height:calc(48px * 2 + var(--BORDER_GAP));flex-wrap:wrap}#game-toolbar .color-picker{flex:1 1 auto}#game-toolbar .colors{flex:1 1 auto}#game-toolbar .colors .color{flex:1 1 auto;aspect-ratio:auto}#game-toolbar .toolbar-group-colors{width:100%;height:48px;margin-bottom:var(--BORDER_GAP)}#game-toolbar .toolbar-group-actions,#game-toolbar .toolbar-group-tools{height:48px;justify-content:center}}@media (orientation:portrait){#load .container .icon{width:50vw;height:50vw}#modal{font-size:1.8vh}#modal .modal-container{width:95vw}#modal .modal-container-info,#modal .modal-container-player,#modal .modal-container-room,#modal .modal-container-settings{width:100%}#home{height:auto;font-size:2vh}#home input{height:4.25vh;width:65%}#home select{height:4.25vh;width:calc(35% - 1.25vh / 2);margin-left:.625vh}#home .button-play{height:7vh}#home .button-create{height:5vh;margin-top:1.25vh}#home .avatar-customizer{padding:1.25vh;margin-top:1.25vh;margin-bottom:1.25vh}#home .avatar-customizer .randomize{width:5vh;height:5vh;right:1.25vh;top:1.25vh;background-size:cover}#home .avatar-customizer .container{width:15vh;height:15vh}#home .avatar-customizer .arrows .arrow{width:5vh;height:5vh}#home .logo-big{margin-top:6vh;margin-bottom:4vh;width:95vw;max-width:65vh}#home .logo-big img{width:100%;height:auto}#home .logo-big .avatar-container{width:100%;margin-top:1.5vh;height:auto}#home .logo-big .avatar-container .avatar{width:10%;height:auto;aspect-ratio:1}#home .panels{flex-direction:column;justify-content:center;align-items:center;width:95vw;max-width:55vh}#home .panel{width:100%;padding:1.75vh}#home .panel-left,#home .panel-right{flex:0 0 auto}#home .news .content{max-height:40vh}#home #tutorial .navigation{height:4vh}
    //#home .bottom{margin-top:5vh}#home .bottom svg{height:2vh}#home .bottom .footer{padding-top:1.25vh;padding-bottom:1.25vh}#home .bottom .footer .section-container{flex-direction:column;align-items:center}#home .bottom .footer .section-container .section{width:95vw;max-width:55vh;padding:1.25vh;margin:0;margin-bottom:1.25vh}#home .bottom .footer .section-container .section h2{margin-bottom:2vh}#home .bottom .footer .section-container .section .icon{width:4vh;height:4vh;top:1vh;left:1vh}#home .panel-left{margin-right:0;margin-bottom:8px}#home .panel-right{margin-left:0;margin-top:8px}#game{display:flex;align-items:center;height:calc(var(--vh) * 100);width:100%;margin-left:0;margin-right:0}#game-invite{font-size:1.3em;height:100%}#game-invite .title{display:none}:root{--BORDER_GAP:calc(var(--vh) * 0.7);--PLAYERS_PER_PAGE:8}#game-wrapper{font-size:calc(var(--vh) * 1);height:100%;width:100%;max-width:70vh;grid-template-areas:"bar      bar" "canvas   canvas" "tools    tools" "players  chat";grid-template-columns:calc(50% - var(--BORDER_GAP) * .5) calc(50% - var(--BORDER_GAP) * .5);grid-template-rows:calc(var(--vh) * 5) min-content calc(var(--vh) * 5) 1fr}#game-wrapper.toolbar-hidden #game-toolbar{display:none}#game-wrapper:not(.room).toolbar-hidden #game-players{grid-area:tools/tools/players/players}#game-wrapper:not(.room).toolbar-hidden #game-chat{grid-area:tools/chat/chat/chat}#game-players{width:100%}#game-players .players-list .player{height:calc(100% / var(--PLAYERS_PER_PAGE));font-size:1.6em}#game-players .players-list .player .player-avatar-container{aspect-ratio:1;height:100%;width:auto}#game-players .players-list .player .player-avatar-container .drawing{aspect-ratio:1;width:auto;height:100%;right:70%;top:-3%}#game-players .players-list .player .player-rank{top:.1vh;left:.2vh}#game-players .players-list .player .player-icons{bottom:5%;left:1%;width:auto;height:50%;aspect-ratio:2}#game-players .players-list .player .player-icons .icon{width:50%;height:100%;margin:0}#game-room{height:100%;font-size:1.2em}#game-room .game-room-group .items .item{font-size:1.3em}
    //
    //#game-room .game-room-group .items .item .key span{line-height:1.3em}
    //
    //#game-toolbar{height:calc(var(--vh) * 5)}
    //#game-toolbar .color-picker-mobile,#game-toolbar .preview,#game-toolbar .sizes,#game-toolbar .sizes .size,#game-toolbar .tool{height:calc(var(--vh) * 5);width:calc(var(--vh) * 5)}#game-toolbar .sizes .container .arrow{width:calc(var(--vh) * 5);height:calc(var(--vh) * 1)}#game-toolbar .toolbar-group-colors{width:auto;height:100%;margin-bottom:0}#game-toolbar .toolbar-group-tools{height:100%}#game-toolbar .toolbar-group-actions{height:100%;justify-content:flex-end}#game-toolbar .colors-mobile.open{display:inline}#game-toolbar .color-picker-mobile{display:inline}#game-toolbar .color-picker{display:none}#game-toolbar .tools-container{justify-content:space-between}#game-toolbar .tools-container .tools:first-child{flex:0 0 auto}#game-bar{font-size:1em}#game-bar .mobile{display:unset}#game-word{font-size:1em;margin:0}#game-word .description{top:0;font-size:1.6em}#game-word .word{top:2vh;font-size:2.6em}#game-clock,#game-round{display:none}.ad-1{width:100%}.ad-2{display:none}#game-logo{display:none;width:100%;height:100%}#game-logo a{display:none}#game-canvas .room{font-size:1.3em}#game-canvas .room .game-room-group .items{flex-direction:row;flex-wrap:wrap}#game-canvas .room .game-room-group .items .item{height:32%;width:32%;flex-direction:column}#game-canvas .room .game-room-group .items .item .key{height:50%;display:flex;align-items:center}#game-canvas .room .game-room-group .items .item .key img{height:80%}#game-canvas .room .game-room-group .items .item .value{height:50%}#game-settings{top:0;right:0;padding:0;width:calc(var(--vh) * 5);height:calc(var(--vh) * 5)}#game-settings .icon{height:100%;width:100%}
    //#game-settings .content{width:100%;padding:0;margin:0}#game-settings #audio,#game-settings #hotkeys,#game-settings #lightbulb{aspect-ratio:1;width:100%;height:auto}
    //#game-chat{height:100%;width:100%;font-size:1.5em}.clickable .key{font-size:1.2em}html[data-mobile-keyboard] #game-keyboard{display:inline}html[data-mobile-keyboard] #game-players{height:calc(100% - var(--BORDER_GAP))}html[data-mobile-keyboard] #game-chat{height:calc(100% - var(--BORDER_GAP))}html[data-mobile-keyboard] #game-chat form{display:none}html[data-mobile-keyboard] #game-wrapper{height:95%}html[data-mobile-keyboard-open]{--PLAYERS_PER_PAGE:4}html[data-mobile-keyboard-open] #game-keyboard .keyboard-wrapper{top:0}html[data-mobile-keyboard-open] #game-keyboard .input .hidden{display:none}html[data-mobile-keyboard-open] #game-keyboard .input .cursor,html[data-mobile-keyboard-open] 
    //
    //#game-keyboard .input span{display:inline}html[data-mobile-keyboard-open] 
    //
    //#game-wrapper{height:70%}html[data-mobile-keyboard-open] #game-players .players-footer{display:none}}
  //};
//}

// TODO: STYLES, MAKE A RESEARCH IF WE CAN USE THEME INSTEAD?
class PanelStyles {
  static Color textColor = const Color(0xfff0f0f0);
  static EdgeInsetsGeometry padding = const EdgeInsets.all(15);
  static BoxDecoration decoration =
   BoxDecoration(
        color: PanelStyles.color,
        borderRadius: GlobalStyles.borderRadius);
  static Color color = const Color.fromRGBO(12, 44, 150, 0.75);
}

class InputStyles {
  static Color color = const Color(0xff2c2c2c);
  static BoxDecoration decoration = BoxDecoration(
      color: Colors.white,
      borderRadius: GlobalStyles.borderRadius,
      border: Border.all(color: const Color(0xff707070)));
}

class GlobalStyles{
  static BorderRadius borderRadius = const BorderRadius.all(Radius.circular(3));
  static Shadow textShadow = const Shadow(color: Color(0x2b000000), offset: Offset(2, 2));
}